config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "application#dashboard"

  resources :api do 
    collection do 
      get :remote_unlock
      post :sms_unlock
      get :users
      get :events
      get :recent_events
    end
  end

  resources :users, except: [:show]
  resources :events do
    collection do
      post :log
    end
  end

  resources :temp_users

  resources :doors do 
    member do 
      put :unlock
    end
  end

  resources :messages do 
    collection do 
      get :poll
      post :confirm
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :events
  validates_length_of :pin, :is => 4, :message => "must be 4 numbers"
  validates_numericality_of :pin, :message => "must only be numbers"
  validates_presence_of :pin, :name

  scope :admin_users, -> { where(admin: true) }
  scope :basic_users, -> { User.all - User.admin_users }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  def new 
    @user = User.new
  end

  # GET /temp_users/1/edit
  def edit
  end

  # PATCH/PUT /temp_users/1
  # PATCH/PUT /temp_users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        Event.pin_changed(@user)
        Message.create(command: Command.find_by(code: "USR"), user: @user)
        format.html { redirect_to root_path, notice: 'Pin successfully updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        flash[:alert] =  @user.errors.full_messages.to_sentence
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temp_users/1
  # DELETE /temp_users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Temp user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:pin, :name)
    end

    def user_create_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :pin %><br>
    <%= f.number_field :pin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Pin</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.pin %></td>
        <td class="pull-right"><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary btn-xs"  %>
        <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', temp_users_path %>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for(@user) do |f| %>
  <div><%= f.label :name %><br />
  <%= f.text_field :name, autofocus: true %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %></div>

  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>

  <div><%= f.submit "Sign up" %></div>
  <div><%= link_to "Back", root_path %></div>
<% end %>