config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "application#dashboard"

  resources :api do 
    collection do 
      get :remote_unlock
      post :sms_unlock
      get :users
      get :events
      get :recent_events
    end
  end

  resources :users, except: [:show]
  resources :events do
    collection do
      post :log
    end
  end

  resources :temp_users

  resources :doors do 
    member do 
      put :unlock
    end
  end

  resources :messages do 
    collection do 
      get :poll
      post :confirm
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :temp_user


  def self.door_unlocked(user)
    if user.class.name == "User"
      Event.create(action: "Door Unlocked via website", user: user)
    else
      Event.create(action: "Door Unlocked via website", temp_user: temp_user)
    end
  end  

  def self.sms_unlock(user=nil, ph_number=nil)
    if user.present?
      Event.create action: "SMS Unlock", user: User.find_by(ph_number: ph_number)
    else
      Event.create action: "Failed SMS Unlock by #{ph_number}"
    end
  end

  def self.android_unlock
    Event.create action: "Android Unlock", user: User.first
  end

  def self.pin_changed(user=nil, temp_user=nil)
    if user.class.name == "User"
      Event.create(action: "Pin Changed", user: user)
    else
      Event.create(action: "Pin Changed", temp_user: temp_user)
    end
  end

  def self.motion_detected(user)
    if user.class.name == "User"
      Event.create(action: "Motion Detected", user: user)
    else
      Event.create(action: "Motion Detected", temp_user: temp_user)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, :log

  # GET /events
  # GET /events.json
  def index
    @events = Event.order("events.created_at DESC").page(params[:page]).per(10)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  #0278315450
  #def sendSMS(to, message, app_key, app_secret)
  def log
    text = request.raw_post
    code = text[0..3]
    result = text[3]
    pin = text[4..7]
    if result == '1'
      event = Event.new(action: "Entry by PIN", user: User.where(pin: pin).first)
    elsif result == '0'
      event = Event.new(action: "Failed PIN attempt")
    elsif result == '!'
      event = Event.new(action: "PIN Lockout")
      sms = SmsGateway.new("http://smsapi.dalek.co.nz/api/sendSMS")
      sms.sendSMS("+64278315450", "Due to repeated attempts of an incorrect PIN, the door is now in PIN Lockout mode", "OTA1Mi40MTIwMjM", "MjYyOS4wODUyMDQwOTgzNzM3RGF0YWNvbXAgMjAxNCAtIERvb3")
    else
      raise 'Unrecognized result flag ' + result
    end
    event.save
    render :nothing => true, :status => 204 
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:action, :user_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action %><br>
    <%= f.text_area :action %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing Events</h1>
<table class="table">
  <thead>
    <tr>
      <th>Action</th>
      <th>User Name</th>
      <th>User Email</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.action %></td>
        <% if event.user.present? %>
          <td><%= event.user.name %></td>
          <td><%= event.user.email %></td>
        <% elsif event.temp_user.present?%>
          <td><%= event.temp_user.name %></td>
          <td></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
        <td><%= event.created_at.strftime("%m/%d/%Y at %I:%M%p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  setTimeout(function(){
   window.location.reload(1);
}, 1000);
</script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Action:</strong>
  <%= @event.action %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>