config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "application#dashboard"

  resources :api do 
    collection do 
      get :remote_unlock
      post :sms_unlock
      get :users
      get :events
      get :recent_events
    end
  end

  resources :users, except: [:show]
  resources :events do
    collection do
      post :log
    end
  end

  resources :temp_users

  resources :doors do 
    member do 
      put :unlock
    end
  end

  resources :messages do 
    collection do 
      get :poll
      post :confirm
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :authenticate_user!
  def dashboard

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def date date
    date.strftime("%d/%m/%y %r")
  end

end

app/views/application/dashboard.html.erb
<div class="row dashboard">
  <div class="col-md-4 column">
    <div class="panel panel-primary dashboard-panel">
      <div class="panel-heading">
        <h3 class="panel-title">Users</h3>
      </div>
      <div class="panel-body dashboard-panel-body">
        <div class="well">
          <h4>Admin Users</h4>
          <%= render "users/index", users: User.admin_users %>
        </div>
        <div class="well">
          <h4>Users</h4>
          <%= render "users/index", users: User.basic_users %>
        </div>
      </div>
      <div class="panel-footer"> 
        <%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
      </div>
    </div>

  </div>
  <div class="col-md-4 column">
   <div class="panel panel-primary dashboard-panel">
     <div class="panel-heading">
      <h3 class="panel-title">Door</h3>
    </div>
    <div class="panel-body dashboard-panel-body">
      <%= render "doors/show", door: Door.first %>
      <br>
      <div align="center">
      <%= link_to "#{image_tag 'default_lock.jpg', size: '200x250', alt: 'Lock', id: "lock_image"}".html_safe, unlock_door_path(Door.first), method: :put,remote: true %>
      </div>
    </div>
  </div>
</div>
<div class="col-md-4 column">
 <div class="panel panel-primary dashboard-panel">
   <div class="panel-heading">
    <h3 class="panel-title">Temporary Users</h3>
  </div>
  <div class="panel-body dashboard-panel-body">
   <div class="well">
    <%= render "temp_users/index", temp_users: TempUser.all %>
  </div>
</div>
<div class="panel-footer "> 
  <%= link_to 'New Temp User', new_temp_user_path, class: "btn btn-primary" %>

</div>
</div>

<script>


</script>