config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  root to: "application#dashboard"

  resources :api do 
    collection do 
      get :remote_unlock
      post :sms_unlock
      get :users
      get :events
      get :recent_events
    end
  end

  resources :users, except: [:show]
  resources :events do
    collection do
      post :log
    end
  end

  resources :temp_users

  resources :doors do 
    member do 
      put :unlock
    end
  end

  resources :messages do 
    collection do 
      get :poll
      post :confirm
    end
  end

end

app/models/door.rb
class Door < ActiveRecord::Base
end

app/controllers/doors_controller.rb
class DoorsController < ApplicationController
  before_action :set_door, only: [:show, :edit, :update, :destroy]

  # GET /doors
  # GET /doors.json
  def index
    @doors = Door.all
  end

  # GET /doors/1
  # GET /doors/1.json
  def show
  end

  # GET /doors/new
  def new
    @door = Door.new
  end

  # GET /doors/1/edit
  def edit
  end

  # POST /doors
  # POST /doors.json
  def create
    @door = Door.new(door_params)

    respond_to do |format|
      if @door.save
        format.html { redirect_to @door, notice: 'Door was successfully created.' }
        format.json { render :show, status: :created, location: @door }
      else
        format.html { render :new }
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doors/1
  # PATCH/PUT /doors/1.json
  def update
    respond_to do |format|
      if @door.update(door_params)
        format.html { redirect_to root_path, notice: 'Door was successfully updated.' }
        format.json { render :show, status: :ok, location: @door }
      else
        format.html { render :edit }
        format.json { render json: @door.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doors/1
  # DELETE /doors/1.json
  def destroy
    @door.destroy
    respond_to do |format|
      format.html { redirect_to doors_url, notice: 'Door was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def unlock 
    Event.door_unlocked(current_user)
    Message.create command: Command.find_by(code: "UNL")
    respond_to do |format|
      format.json { head :no_content  }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_door
      @door = Door.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def door_params
      params.require(:door).permit(:name)
    end
  end

app/helpers/doors_helper.rb
module DoorsHelper
end

app/views/doors/_form.html.erb
<%= form_for(@door) do |f| %>
  <% if @door.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@door.errors.count, "error") %> prohibited this door from being saved:</h2>

      <ul>
      <% @door.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doors/_show.html.erb
<p>
  <strong>Name:</strong>
  <%= door.name %>
</p>

<%= link_to 'Edit', edit_door_path(door), class: "btn btn-primary btn-xs"  %>

app/views/doors/edit.html.erb
<h1>Editing door</h1>

<%= render 'form' %>

<%= link_to 'Show', @door %> |
<%= link_to 'Back', doors_path %>

app/views/doors/index.html.erb
<h1>Listing doors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doors.each do |door| %>
      <tr>
        <td><%= door.name %></td>
        <td><%= link_to 'Show', door %></td>
        <td><%= link_to 'Edit', edit_door_path(door) %></td>
        <td><%= link_to 'Destroy', door, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Door', new_door_path %>

app/views/doors/new.html.erb
<h1>New door</h1>

<%= render 'form' %>

<%= link_to 'Back', doors_path %>